### ISSUE TITLE
DEVELOPMENT: time_binning()

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/palaeoverse#10]
Develop time_binning() function

Functionality:

- [x] bin in all
- [x] bin in majority
- [x] bin by midpoint
- [x] bin randomly
- [x] bin threshold
- [x] bin via uniform distribution with replicates (generate point estimates)

**Comment by KEichenseer** [comment]
Great Job Lewis (and Chris?) . I did some tests, it all seems to work except for the binning at large bin sizes (see below). These are the changes I propose:

- [ ] remove `equal` argument: `size` is sufficient. Set default of `size` to `FALSE`, if user specifies a number, then use equal length time bins
- [ ] set `plot` default to `FALSE`: I don't think the user usually doesn't want to plot these intervals when generating time bins.
- [ ] The first bin can be substantially shorter than subsequent bins if long bin sizes are used. Change to generate more uniform bin sizes. Example: time_bins(interval = c("Albian", "Meghalayan"), equal = TRUE, size = 100)
- [ ] add a column called something like "level" to indicate that the bins were grouped on stage, epoch, ... level
- [ ] allow negative ages as arguments to `assign`
- [ ] Input allows epochs, periods ect., but `GTS2020$interval_name` returns only stages. Should return table with stage, epoch, ... column
- [ ] return intervals of time bins as a list of vectors composed of individual interval names, rather than strings with multiple intervals for easier handling in data analysis
- [ ] description unclear: In what way is the mean minimised? I thought the mean durations should be as equal as possible
