### ISSUE TITLE
AUDIT: lat_bins()

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/palaeoverse#5]
The lat_bins() function is now ready for auditing. Sofía and Lucas could you please now audit the code/documentation and check it is behaving as expected?

Please also document any tests you throw at it and bugs you find. This will help with developing the automated testing for later.

For now, I would suggest creating your own branch and proofing the code there. However, if you prefer we can also meet online to discuss any issues that need resolving.

Thank you!!!

- [ ] Sofía's audit complete
- [ ] Lucas' audit complete

**Comment by Buffan3369** [comment]
Lewis, everything works perfectly well and all the documentations are clear! However, I have 2 sugestions:

1. Although it doesn't change the output, line 60 and 65, you are using twice the name "df" for two different things, which may be a bit confusing. I would suggest changing the first one (name of the sequential vector giving the latitudinal scale) to something like "scl" or "lat_scale". I'm going to pull a request anyway.

2. I totally understand your ambitions with the "fit" argument. The fact is that, if one user specifies a bin size that is not a factor of 180, the output will by default return an exact binning of that size, naturally ommiting extremal portions of the [-90, 90] latitudinal spectrum. There is no possibility to tune that (e.g. saying "I want the southern pole region to be included but not the northern pole one"). I'm wondering who would want to exclude some pre-defined regions like that, with the risk to loose samples that would fall there. I'm probably wrong but wouldn't it make more sense to just implement the "fit=TRUE" case as a conditionnal situation triggered by "size = x such as 180%%x != 0"?
Otherwise, if one user REALLY wants a binnig that is not a factor of 180, maybe could we implement the possibility for him/her to choose the zones of the map to exclude? Do you see what I mean?
 
But again, the function works very well!

**Comment by LewisAJones** [comment]
> 

Thanks for your thoughtful comments Lucas! I will address them point by point.

1. I do not think this is really an issue. In fact, it prevents too many additional variables being generated and taking up more memory than neccesary (though not really an issue for the size of objects here!). 
2. I see your point here, and I think it is pretty valid. However, I think how the function is implemented gives greater control to the user without any surprises. I don't think we should force a specific latitudinal bin size on the user as we do not really know their intentions. However, I agree that 99% of time, users will want to cover the entire latitudinal range. I will leave the function as is for now, but this something to get feedback on from users.

Thanks again!

**Comment by Buffan3369** [comment]
Hi Lewis,

1.  Okay, I see the point. I think my mind is a bit OCD. Maybe could we leave a comment in the code saying that these 2 dfs are different? But it's just a suggestion, with your justification it seems fair enough to leave the code as it is.

2. Perfect! Let's see if the question is raised by the users then :)

All in all, you did something really neat!
